# Generated by Django 5.1.5 on 2025-03-24 13:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image1', models.ImageField(upload_to='product_images/')),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_variant', models.JSONField(blank=True, null=True)),
                ('product_available', models.BooleanField(default=False)),
                ('product_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_image', models.ImageField(upload_to='card_images/')),
                ('card_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_card.product')),
            ],
        ),
    ]
