# Generated by Django 5.1.5 on 2025-03-25 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_card', '0003_product_product_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_video_link',
        ),
    ]
