# Generated by Django 5.1.5 on 2025-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_card', '0004_remove_product_product_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
