# Generated by Django 5.1.5 on 2025-03-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_card', '0006_productcategory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_hsc_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
