# Generated by Django 5.1.5 on 2025-04-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_card', '0007_product_product_gst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
