# Generated by Django 5.1.5 on 2025-03-04 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EASY_SHIP', 'Easy Ship'), ('FBA', 'Fulfilled by Amazon'), ('SELLER_FLEX', 'Seller Flex')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='fee_calculator.category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cost', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('weight', models.FloatField()),
                ('dimensions', models.JSONField()),
                ('gst', models.FloatField()),
                ('referral_fee', models.FloatField()),
                ('closing_fee', models.FloatField()),
                ('total_fee', models.FloatField()),
                ('gross_profit', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_calculator.category')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_calculator.amazonprogram')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_calculator.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_fee_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('closing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_handling_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pick_pack_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage_fee_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_processing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_calculator.category')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_calculator.amazonprogram')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee_calculator.subcategory')),
            ],
            options={
                'unique_together': {('category', 'subcategory', 'program')},
            },
        ),
    ]
