# Generated by Django 5.1.5 on 2025-03-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='referral_fee_eq',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exact amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='referral_fee_gte',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Greater than or equal to amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='referral_fee_lte',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Less than or equal to amount', max_digits=10, null=True),
        ),
    ]
