# Generated by Django 5.1.5 on 2025-03-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_calculator', '0002_subcategory_referral_fee_eq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Item price', max_digits=10, null=True),
        ),
    ]
