# Generated by Django 5.1.5 on 2025-03-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_calculator', '0003_subcategory_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='return_processing_fee',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='storage_fee_per_month',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='referral_fee_eq',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='referral_fee_gte',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='referral_fee_lte',
        ),
    ]
