# Generated by Django 5.1.5 on 2025-03-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_calculator', '0004_remove_feestructure_return_processing_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='pick_pack_fee',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='weight_handling_fee',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='condition',
            field=models.CharField(blank=True, choices=[('gte', 'Greater than or equal to'), ('lte', 'Less than or equal to'), ('eq', 'Equal to'), ('gt', 'Greater than'), ('lt', 'Less than')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('Pick and Pack Fee', 'Pick and Pack Fee'), ('Technology Fee', 'Technology Fee')], max_length=255, null=True),
        ),
    ]
