# Generated by Django 5.1.5 on 2025-03-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_calculator', '0005_remove_feestructure_pick_pack_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
