# Generated by Django 5.1.5 on 2025-03-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_calculator', '0008_remove_feestructure_closing_fee_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
    ]
