# Generated by Django 5.1.5 on 2025-03-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_calculator', '0009_alter_feestructure_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='is_exception',
            field=models.BooleanField(default=False),
        ),
    ]
