# Generated by Django 5.1.5 on 2025-03-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_calculator', '0010_subcategory_is_exception'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonprogram',
            name='closing_fee',
        ),
        migrations.RemoveField(
            model_name='amazonprogram',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='amazonprogram',
            name='fee_value',
        ),
        migrations.AlterField(
            model_name='amazonprogram',
            name='name',
            field=models.CharField(choices=[('EASY_SHIP', 'Easy Ship Prime'), ('FBA', 'FBA'), ('SELLER_FLEX', 'Seller Flex')], max_length=20),
        ),
    ]
