# Generated by Django 5.1.5 on 2025-02-21 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(null=True, upload_to='agents/photos/')),
                ('name', models.CharField(max_length=100, null=True)),
                ('agent_passcode', models.CharField(max_length=128, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('pan_number', models.CharField(max_length=10, null=True)),
                ('aadhar_number', models.CharField(max_length=12, null=True)),
                ('address', models.TextField(null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('qualification_file', models.FileField(null=True, upload_to='agents/qualification_files/')),
                ('bank_account_holder_name', models.CharField(max_length=100, null=True)),
                ('bank_account_number', models.CharField(max_length=15, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('branch_name', models.CharField(max_length=100, null=True)),
                ('bank_ifsc_code', models.CharField(max_length=10, null=True)),
                ('cancelled_cheque_file', models.FileField(null=True, upload_to='agents/cancelled_cheque_files/')),
                ('offer_letter_file', models.FileField(null=True, upload_to='agents/offer_letter_files/')),
                ('bank_statement_file', models.FileField(null=True, upload_to='agents/bank_statement_files/')),
                ('increment_letter_file', models.FileField(null=True, upload_to='agents/increment_letter_files/')),
                ('pay_slip_file', models.FileField(null=True, upload_to='agents/pay_slip_files/')),
                ('experience_letter_file', models.FileField(null=True, upload_to='agents/experience_letter_files/')),
                ('leave_letter_file', models.FileField(null=True, upload_to='agents/leave_letter_files/')),
                ('addhar_card_file', models.FileField(null=True, upload_to='agents/addhar_card_files/')),
                ('pan_card_file', models.FileField(null=True, upload_to='agents/pan_card_files/')),
                ('experience', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('no_of_meetings', models.IntegerField(default=0)),
                ('no_of_meetings_completed', models.IntegerField(default=0)),
                ('no_of_sales', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('terms_and_conditions', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('agent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agentuser')),
            ],
        ),
        migrations.CreateModel(
            name='AgentCoorporate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('agent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agentuser')),
            ],
        ),
        migrations.CreateModel(
            name='DemoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=15)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('demo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('agent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agentuser')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_duration', models.DurationField(null=True)),
                ('meeting_audio', models.FileField(null=True, upload_to='customer_support/meeting_audio/')),
                ('meeting_image', models.FileField(null=True, upload_to='customer_support/meeting_image/')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('duration', models.CharField(default='', max_length=100)),
                ('agent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agentuser')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
            },
        ),
        migrations.AddField(
            model_name='agentuser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.policy'),
        ),
    ]
