# Generated by Django 5.1.5 on 2025-04-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_websitepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='public_slug',
            field=models.SlugField(blank=True, help_text='Public URL slug for sharing', max_length=100, null=True, unique=True),
        ),
    ]
