# Generated by Django 5.1.5 on 2025-04-19 11:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_website_public_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website_categories/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='website.websitecategory')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='website.website')),
            ],
            options={
                'verbose_name_plural': 'Website Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('website', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='WebsiteProduct',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image1', models.ImageField(upload_to='website_products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='website_products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='website_products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='website_products/')),
                ('hsn_code', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('variants', models.JSONField(blank=True, null=True)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='website.websitecategory')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='website.website')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('website', 'slug')},
            },
        ),
    ]
