# Generated by Django 5.1.5 on 2025-04-24 12:18

from django.db import migrations

def cleanup_duplicate_websites(apps, schema_editor):
    Website = apps.get_model('website', 'Website')
    User = apps.get_model('auth', 'User')
    
    for user in User.objects.all():
        # Get all websites for this user, ordered by creation date
        user_websites = Website.objects.filter(user=user).order_by('-created_at')
        
        # Keep only the latest website, delete the rest
        if user_websites.count() > 1:
            latest_website = user_websites.first()
            user_websites.exclude(id=latest_website.id).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_websitecategory_websiteproduct'),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_websites, migrations.RunPython.noop),
    ]
