# Generated by Django 5.1.5 on 2025-04-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_website_one_website_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteproduct',
            name='specifications',
            field=models.JSONField(blank=True, help_text='Product specifications as key-value pairs', null=True),
        ),
    ]
