from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', MasterAdminLogin, name='masteradmin_login'),
    path('dashboard/', MasterAdminView.as_view(), name='masteradmin_dashboard'),
    path('signup/', Signup, name='signup'),
    path('agents/', AgentsView.as_view(), name='agents'),
    path('subscription/', SubscriptionView.as_view(), name='subscription'),
    path('apps/', AppsView.as_view(), name='apps'),
    path('feedbacks/', FeedbacksView.as_view(), name='feedbacks'),
    path('users/', UsersView.as_view(), name='users'),
    path('customer_support/', CustomerSupportView.as_view(), name='customer_support'),
    path('settings/', SettingView.as_view(), name="settings"),
    path('sales/', SalesView.as_view(), name="sales"),
    path('add_agent/', AddAgentView.as_view(), name='add_agent'),
    path('create_subscription/', CreateSubscriptionView.as_view(), name='create_subscription'),
    path('delete_subscription/', DeleteSubscriptionView.as_view(), name='delete_subscription'),
    path('edit_subscription/', EditSubscriptionView.as_view(), name='edit_subscription'),
    path('ticket/', TicketView.as_view(), name='ticket'),
    path('create_coupon/', CreateCouponView.as_view(), name='create_coupon'),
    path('export_data/', ExportDataView.as_view(), name='export_data'),
    path('delete_coupon/', DeleteCouponView.as_view(), name='delete_coupon'),
    path('agent/register/<str:passcode>/', AddAgentView.as_view(), name='agent_register'),
    path('agent_details/', AgentDetailsView.as_view(), name='agent_details'),
    path('approve-agent/<str:agent_id>/', ApproveAgentView.as_view(), name='approve_agent'),
    path('departments/', DepartmentsView.as_view(), name='departments'),
    path('departments/<uuid:department_id>/', DepartmentsView.as_view(), name='department_detail'),
    path('customer_support/', CustomerSupportMAView.as_view(), name='customer_supportMA'),
    path('employees/', AllEmployeesView.as_view(), name='allemployees'), 
    path('mastersupport/', MasterSupportView.as_view(), name='mastersupport'),
    path('create_note/', CreateNoteView.as_view(), name='create_note'),
    path('create_employee/', CreateEmployeeView.as_view(), name='create_employee'),
    # path('download_documents/<int:agent_id>/', DownloadDocumentsView.as_view(), name='download_documents'),
    path('reject-agent/<str:agent_id>/', RejectAgentView.as_view(), name='reject_agent'),
    path('mark_employee_as_active/<str:employee_id>/', MarkEmployeeAsActiveView.as_view(), name='mark_employee_as_active'),
    path('mark_employee_as_inactive/<str:employee_id>/', MarkEmployeeAsInactiveView.as_view(), name='mark_employee_as_inactive'),
    path('reject_employee/<str:employee_id>/', RejectEmployeeView.as_view(), name='reject_employee'),
    path('delete_department/<str:department_id>/', DeleteDepartmentView.as_view(), name='delete_department'),
    path('suspended_agents/', SuspendedAgentsView.as_view(), name='suspended_agents'),
    # path('login/', views.login, name='login'),
    path('login/', MasterAdminLogin, name='login'),
    path('logout/', logout, name='masteradmin_logout'),
    path('all_agents/', AllAgentsView.as_view(), name='all_agents'),
    path('agent_performance/', AgentPerformanceView.as_view(), name='agent_performance'),
    path('add_support/', AddSupportView.as_view(), name='add_support'),
    path('create_notification/', CreateAgentsNotificationView.as_view(), name='create_notification'),
    path('support_department/', SupportDepartmentView.as_view(), name='support_department'),
    path('whats_on_mind/', WhatsOnMindView.as_view(), name='whats_on_mind'),
    path('send_agent_notification/', SendAgentNotificationView.as_view(), name='send_agent_notification'),
    path('send_support_notification/', SendSupportNotificationView.as_view(), name='send_support_notification'),
    path('send_employee_notification/', SendEmployeeNotificationView.as_view(), name='send_employee_notification'),
    path('user_details/',UserDetailsView.as_view(), name='user_details'),
    path('approve_employee/<str:employee_id>/', approve_employee, name='approve_employee'),
    path('reject_employee/<str:employee_id>/', reject_employee, name='reject_employee'),
    path('approve_support/<str:support_id>/', approve_support, name='approve_support'),
    path('reject_support/<str:support_id>/', reject_support, name='reject_support'),
    path('delete_support_department/<str:department_id>/', DeleteSupportDepartmentView.as_view(), name='delete_support_department'),
    path('ai_prompt/', AI_PromptView.as_view(), name='ai_prompt'),
    path('create_ticket/', CreateTicketView.as_view(), name='create_ticket'),
    path('mark_agent_as_active/<str:agent_id>/', MarkAgentAsActiveView.as_view(), name='mark_agent_as_active'),
    path('mark_agent_as_inactive/<str:agent_id>/', MarkAgentAsInactiveView.as_view(), name='mark_agent_as_inactive'),
    path('reject_agent/<str:agent_id>/', RejectAgentView.as_view(), name='reject_agent'),
    path('total_subscription/', TotalSubscriptionView.as_view(), name='total_subscription'),
    path('suspend_subscription/<str:subscription_id>/', SuspendSubscriptionView.as_view(), name='suspend_subscription'),
    path('user_policy/', CreateUserPolicy.as_view(), name='user_policy'),
    path('create_user/', CreateUserView.as_view(), name='create_user'),
    path('notes/<str:note_id>/pin/', MarkQuickNoteAsPinnedView.as_view(), name='mark_quick_note_as_pinned'),
    path('get-feedbacks/', get_feedbacks, name='get_feedbacks'),
    path('delete_user_policy/<str:policy_id>/', DeleteUserPolicy.as_view(), name='delete_user_policy'),
    path('suspend_support/<str:support_id>/', suspend_support, name='suspend_support'),
    path('mark_support_as_active/<str:support_id>/', mark_support_as_active, name='mark_support_as_active'),
    path('reject_support/<str:support_id>/', reject_support, name='reject_support'),
    path('update_support_salary/', update_support_salary, name='update_support_salary'),
    path('assign_to_me/<str:ticket_id>/', AssignToMeView.as_view(), name='assign_to_me'),
    path('get_support_users/<uuid:department_id>/', GetSupportUsersView.as_view(), name='get_support_users'),
    path('assign_ticket/<uuid:ticket_id>/', AssignTicketView.as_view(), name='assign_ticket'),
    path('debug_ticket/<uuid:ticket_id>/', DebugTicketAssignmentView.as_view(), name='debug_ticket'),
    path('my_tickets/', MyTicketsView.as_view(), name='my_tickets'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

