# Generated by Django 5.1.5 on 2025-02-21 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(null=True, upload_to='employee/photos/')),
                ('name', models.CharField(max_length=100, null=True)),
                ('employee_passcode', models.CharField(max_length=128, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('pan_number', models.CharField(max_length=10, null=True)),
                ('aadhar_number', models.CharField(max_length=12, null=True)),
                ('address', models.TextField(null=True)),
                ('dob', models.DateField(null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('qualification_file', models.FileField(null=True, upload_to='employee/qualification_files/')),
                ('bank_account_holder_name', models.CharField(max_length=100, null=True)),
                ('bank_account_number', models.CharField(max_length=15, null=True)),
                ('bank_name', models.CharField(max_length=100, null=True)),
                ('branch_name', models.CharField(max_length=100, null=True)),
                ('bank_ifsc_code', models.CharField(max_length=10, null=True)),
                ('cancelled_cheque_file', models.FileField(null=True, upload_to='employee/cancelled_cheque_files/')),
                ('offer_letter_file', models.FileField(null=True, upload_to='employee/offer_letter_files/')),
                ('bank_statement_file', models.FileField(null=True, upload_to='employee/bank_statement_files/')),
                ('increment_letter_file', models.FileField(null=True, upload_to='employee/increment_letter_files/')),
                ('pay_slip_file', models.FileField(null=True, upload_to='employee/pay_slip_files/')),
                ('experience_letter_file', models.FileField(null=True, upload_to='employee/experience_letter_files/')),
                ('leave_letter_file', models.FileField(null=True, upload_to='employee/leave_letter_files/')),
                ('addhar_card_file', models.FileField(null=True, upload_to='employee/addhar_card_files/')),
                ('pan_card_file', models.FileField(null=True, upload_to='employee/pan_card_files/')),
                ('experience', models.CharField(max_length=100, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('no_of_meetings', models.IntegerField(default=0)),
                ('no_of_meetings_completed', models.IntegerField(default=0)),
                ('no_of_sales', models.IntegerField(default=0)),
                ('total_sales', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.policy')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCoorperate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('support_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('support_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
