# Generated by Django 5.1.5 on 2025-03-28 12:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_offerletter'),
        ('invoicing', '0010_alter_invoice_invoice_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('qr_code_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_and_coordinates', models.JSONField(blank=True, null=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoicing.company')),
            ],
        ),
    ]
