# Generated by Django 5.1.5 on 2025-03-30 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='secret_key',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
    ]
