# Generated by Django 5.1.5 on 2025-03-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='number_of_days_attended',
            field=models.IntegerField(default=0),
        ),
    ]
