# Generated by Django 5.1.5 on 2025-03-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_employee_number_of_days_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/'),
        ),
    ]
