# Generated by Django 5.1.5 on 2025-03-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_employee_attendance_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
