# Generated by Django 5.1.5 on 2025-03-30 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_employee_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
    ]
