# Generated by Django 5.1.5 on 2025-03-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_remove_device_user_agent_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_status',
            field=models.CharField(default='not_marked', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_attendance_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
