# Generated by Django 5.1.5 on 2025-03-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_employee_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_verification',
            field=models.BooleanField(default=False),
        ),
    ]
