# Generated by Django 5.1.5 on 2025-04-13 11:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_employee_attendance_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_identification_number', models.CharField(blank=True, max_length=255, null=True)),
                ('company_gst_number', models.CharField(blank=True, max_length=255, null=True)),
                ('company_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.company'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.company'),
        ),
    ]
