# Generated by Django 5.1.5 on 2025-04-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_company_alter_employee_company_alter_qrcode_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
