# Generated by Django 5.1.5 on 2025-04-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_folder_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='folder_logos/'),
        ),
    ]
