# Generated by Django 5.1.5 on 2025-03-18 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_type', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=255)),
                ('urls', models.JSONField()),
                ('keyword_screenshots', models.JSONField()),
                ('product_images', models.JSONField(default=list, help_text='List of base64 encoded product images')),
                ('product_specs', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
