# Generated by Django 5.1.5 on 2025-03-25 18:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('company_gst_number', models.CharField(max_length=255)),
                ('company_mobile_number', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_signature', models.ImageField(blank=True, null=True, upload_to='company_signature/')),
                ('company_invoice_prefix', models.CharField(max_length=255)),
                ('company_bank_name', models.CharField(max_length=255)),
                ('company_bank_account_number', models.CharField(max_length=255)),
                ('company_bank_ifsc_code', models.CharField(max_length=255)),
                ('company_upi_id', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('company_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('billing_name', models.CharField(max_length=255)),
                ('billing_phone', models.CharField(max_length=255)),
                ('billing_gst_number', models.CharField(max_length=255)),
                ('billing_address', models.TextField()),
                ('billing_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoicing.company')),
            ],
        ),
    ]
