# Generated by Django 5.1.5 on 2025-03-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
