# Generated by Django 5.1.5 on 2025-03-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_invoice_invoice_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
