# Generated by Django 5.1.5 on 2025-03-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_invoice_invoice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
