# Generated by Django 5.1.5 on 2025-03-27 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_invoice_payment_screenshot_invoice_payment_status'),
        ('product_card', '0007_product_product_gst_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='billing_product',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='billing_quantity',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='billing_total',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='billing_type',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='billing_unit_type',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_card.product'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Proforma Invoice', 'Proforma Invoice'), ('Paid Invoice', 'Paid Invoice'), ('Unpaid Invoice', 'Unpaid Invoice')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_unit_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
