# Generated by Django 5.1.5 on 2025-03-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_remove_billing_billing_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Proforma Invoice', 'Proforma Invoice'), ('Invoice', 'Invoice')], max_length=255, null=True),
        ),
    ]
