# Generated by Django 5.1.5 on 2025-03-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_product',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
