# Generated by Django 5.1.5 on 2025-04-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0010_alter_invoice_invoice_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='use_billing_address',
            field=models.BooleanField(default=True),
        ),
    ]
