# Generated by Django 5.1.5 on 2025-04-12 09:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_user_password'),
        ('invoicing', '0011_invoice_shipping_address_invoice_shipping_pincode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipent',
            fields=[
                ('recipent_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recipent_mobile_number', models.CharField(max_length=255)),
                ('security_code', models.CharField(max_length=255)),
                ('passcode', models.CharField(max_length=255)),
                ('recipent_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipent_updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(blank=True, to='invoicing.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
