# Generated by Django 5.1.5 on 2025-04-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_recipent'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='billing_pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
