# Generated by Django 5.1.5 on 2025-04-26 12:34

import django.db.models.deletion
from django.db import migrations, models
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=10)),
                ('data_type', models.CharField(max_length=10)),
                ('results_count', models.IntegerField(default=0)),
                ('excel_file', models.FileField(upload_to='mining_results/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_history', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Mining Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
