# Generated by Django 5.1.5 on 2025-04-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_miner', '0001_initial'),
    ]

    operations = [
    ]
