# Generated by Django 5.1.5 on 2025-04-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_userpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_payment_mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_payment_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
