# Generated by Django 5.1.5 on 2025-04-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_feedback_id_alter_feedback_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedbacks',
        ),
    ]
