# Generated by Django 5.1.5 on 2025-04-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customersupport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportuser',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
