# Generated by Django 5.1.5 on 2025-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0002_tickets_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeenotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportnotification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
