# Generated by Django 5.1.5 on 2025-02-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0003_agentnotification_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsonmind',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
