# Generated by Django 5.1.5 on 2025-02-22 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('customersupport', '0001_initial'),
        ('employee', '0001_initial'),
        ('masteradmin', '0004_whatsonmind_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsonmind',
            name='is_read',
        ),
        migrations.CreateModel(
            name='WhatsOnMindReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agentuser')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customersupport.supportuser')),
                ('whats_on_mind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masteradmin.whatsonmind')),
            ],
            options={
                'unique_together': {('whats_on_mind', 'agent'), ('whats_on_mind', 'employee'), ('whats_on_mind', 'support')},
            },
        ),
    ]
