# Generated by Django 5.1.5 on 2025-03-19 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0005_remove_whatsonmind_is_read_whatsonmindreadstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
