# Generated by Django 5.1.5 on 2025-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0006_ai_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_prompt',
            name='platform',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
