# Generated by Django 5.1.5 on 2025-04-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0007_alter_ai_prompt_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
