# Generated by Django 5.1.5 on 2025-04-03 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_last_payment_amount_user_last_payment_date_and_more'),
        ('masteradmin', '0008_subscription_is_paused_subscription_is_suspended'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masteradmin.usernotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
            options={
                'unique_together': {('notification', 'user')},
            },
        ),
        migrations.AddField(
            model_name='usernotification',
            name='users',
            field=models.ManyToManyField(through='masteradmin.UserNotificationRecipient', to='User.user'),
        ),
    ]
