# Generated by Django 5.1.5 on 2025-04-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0009_usernotification_usernotificationrecipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notifications/'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
