# Generated by Django 5.1.5 on 2025-04-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0011_quicknotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='name',
            new_name='mobile_number',
        ),
    ]
