# Generated by Django 5.1.5 on 2025-04-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0012_rename_name_tickets_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='priority',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=255, null=True),
        ),
    ]
